Merge indentation level and line number hotkey
SingleSemesterSnobs/Mind_Reader pull request #11
Opened 2021-11-16 21:18 UTC by CalWooten95

2021-11-16 22:02 UTC, jakergrossman requested changes

2021-11-16 22:02 UTC, jakergrossman commented on src/commands.ts
> +    let i = 0;
```suggestion
```

2021-11-17 22:34 UTC, CalWooten95 commented on src/commands.ts
> +    let i = 0;
I agree with that idea and I have made the changes you have suggested thanks!

2021-11-17 23:08 UTC, jakergrossman approved these changes

2021-11-18 04:12 UTC, sophiadrewfs approved these changes
looks good!

2021-11-18 04:12 UTC, merged