Add Navigations Keys
SingleSemesterSnobs/Mind_Reader pull request #8
Opened 2021-11-09 18:36 UTC by JosiahMoses

2021-11-09 21:12 UTC, jakergrossman requested changes
Looks good! Fix spelling on `showAllSymboles` and I'll approve to merge.

2021-11-09 21:12 UTC, jakergrossman commented on package.json
> +				"command": "mind-reader.showAllSymboles",
```suggestion
				"command": "mind-reader.showAllSymbols",
```

2021-11-09 21:12 UTC, jakergrossman commented on src/commands.ts
> +    name: 'mind-reader.showAllSymboles',
```suggestion
    name: 'mind-reader.showAllSymbols',
```

2021-11-16 17:45 UTC, JosiahMoses commented
Fixed Typos in src/commands.ts and package.json

2021-11-16 17:56 UTC, merged